config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'customers' => 'users#customer_list', :as => :customers
    post 'create_customer' => 'users#create_user', :as => :create_customer
    get 'change_status' => 'users#change_status', :as => :change_status
    get 'edit_customer' => 'users#edit_user', :as => :edit_customer
    patch 'update_customer' => 'users#update_user', :as => :update_customer
    get 'agents' => 'users#agent_list', :as => :agents
    post 'create_agent' => 'users#create_user', :as => :create_agent
    get 'edit_agent' => 'users#edit_user', :as => :edit_agent
    post 'update_agent' => 'users#update_user', :as => :update_agent
    get 'delete_agent' => 'users#delete_user', :as => :delete_agent
    get 'dashboard' => 'users#dashboard', :as => :dashboard
    get 'edit_profile' => 'users#edit_profile', :as => :edit_profile
    patch 'update_profile' => 'users#update_profile', :as => :update_profile
  end
  
  
  as :vechile do
    get 'vehicle_list' => "vehicles#vehicle_list", :as => :vehicle_list
    post 'create_vehicle' => "vehicles#create_vehicle", :as => :create_vehicle
    patch 'update_vehicle' => "vehicles#update_vehicle", :as => :update_vehicle
    get 'edit_vehicle' => "vehicles#edit_vehicle", :as => :edit_vehicle
    get 'destroy_vehicle' => "vehicles#destroy_vehicle", :as => :destroy_vehicle
  end
  
  as :route do
    get 'route_list' => "routes#route_list", :as => :route_list
    post 'create_route' => "routes#create_route", :as => :create_route
    patch 'update_route' => "routes#update_route", :as => :update_route
    get 'edit_route' => "routes#edit_route", :as => :edit_route
    get 'destroy_route' => "routes#destroy_route", :as => :destroy_route
  end
  
  as :trip do
    get 'trip_list' => "trips#trip_list", :as => :trip_list
    post 'create_trip' => "trips#create_trip", :as => :create_trip
    patch 'update_trip' => "trips#update_trip", :as => :update_trip
    get 'edit_trip' => "trips#edit_trip", :as => :edit_trip
    get 'destroy_trip' => "trips#destroy_trip", :as => :destroy_trip
    get 'stop_tracking_trip' => "trips#stop_tracking_trip", :as => :stop_tracking_trip
  end
  
  root 'home#index'
  get '/user' => "home#index", :as => 'user'
  get '/validate_authentication' => "tracking#validate_authentication", :as => 'validate_authentication'
  get '/get_trip' => "tracking#get_trip", :as => 'get_trip'
  post '/save_position' => "tracking#save_position", :as => 'save_position'
  post "/trip_details" => "home#trip_details", :as => "trip_details"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  uuid_it
  belongs_to :route
  has_many :trip_details
  belongs_to :user
  
  validates :tracking_code, :presence=> true
  
  def stop_tracking
    self.update_attributes(:track_status => false)
  end



  # Class methods
  class << self
    def fetch_current_trip
      Trip.find_by_track_status_and_delete_status(true, false)
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :set_route
  layout "map"
  
  def trip_list
    if @current_trip.nil?
      @current_trip = Trip.new
    end
    puts @current_trip.inspect
    @previous_trips = @route.get_previous_trips.paginate(:page => 1, :per_page => 10)
    respond_to do |format|
      format.html {render :action => "trip_list"}
      format.json { render json: @trips }
    end
  end

  def create_trip
    @trip = current_user.trips.new(trip_params)
    @trip.route_id = @route.id
    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_list_path(:rid => @route.uuid), notice: 'Trip was successfully created.' }
      else
        @previous_trips = @route.get_previous_trips.paginate(:page => 1, :per_page => 10)
        format.html { render action: "trip_list" }
      end
    end
  end

  def update_trip
    @trip = Trip.find_by_uuid(params[:id])

    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_list_path(:rid => @route.uuid), notice: 'Trip was successfully updated.' }
      else
        @previous_trips = @route.get_previous_trips.paginate(:page => 1, :per_page => 10)
        format.html { render action: "trip_list" }
      end
    end
  end

  def stop_tracking_trip
    @trip = Trip.find_by_uuid(params[:id])
    @trip.stop_tracking

    respond_to do |format|
      format.html { redirect_to trip_list_path(:rid => @route.uuid), notice: 'Stopped tracking successfully.' }
    end
  end
  
  private 
  
  def set_route
    @route = Route.find_by_uuid(params[:rid])
    @current_trip = @route.get_current_trip    
  end
  
  def trip_params
    params.require(:trip).permit(:created_by, :delete_status, :route_id, :track_status, :tracking_code)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_edit.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>Edit Trip</h5>
  <ul class="nav nav-list">
    <%= form_for(@current_trip, :url => update_trip_path(:id => @current_trip.uuid, :rid => @route.uuid)) do |f| %>
        <% if @current_trip.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@current_trip.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @current_trip.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :tracking_code, :placeholder => 'Tracking Code*' %>
        </div>
        <%= f.submit "Update Trip", :class => "btn btn-info", :id => "track" %>
        <%= f.button "Stop Tracking", :class => "btn btn-danger confirm", :id => "stoptrack", :url => stop_tracking_trip_path(:id => @current_trip.uuid, :rid => @route.uuid) %>
    <% end %>
  </ul>
</div>

app/views/trips/_new.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>New Trip</h5>
  <ul class="nav nav-list">
    <%= form_for(@current_trip, :url => create_trip_path(:rid => @route.uuid)) do |f| %>
        <% if @current_trip.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@current_trip.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @current_trip.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :tracking_code, :placeholder => 'Tracking Code' %>
        </div>
        <%= f.submit "Create Trip", :class => "btn btn-info", :id => "track" %>
    <% end %>
  </ul>
</div>

app/views/trips/_previous_trips.html.erb
<% if !@previous_trips.blank?  %>
<div class="navbar-inner">
    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
      <h5>Previous Trips</h5>
      <% @previous_trips.each do |prev_trip| %>
        <li><%= link_to "<i class='icon-chevron-right'></i> #{prev_trip.created_at.strftime("%b %d, %Y")}".html_safe, "#"   %></a></li>
      <% end %>
    </ul>
</div>
<% end %>

app/views/trips/trip_list.html.erb
<div class="span3" id="sidebar">
  <% if @route.status %>
    <% if @current_trip != nil && @current_trip.id != nil %>
      <%= render "edit" %>
    <% else %>
      <%= render "new" %>
    <% end %>
  <% end %>
    <%= render "previous_trips" %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
        <% if current_user.user_type == User::ADMIN %>
          <li><%= link_to "Customers", customers_path %><span class="divider">/</span></li>
        <% end %> 
        <li><%= link_to "Vehicles", vehicle_list_path(:id => @route.user.uuid) %><span class="divider">/</span></li>
        <li><%= link_to "Routes", route_list_path(:id => @route.user.uuid, :vid => @route.vehicle.uuid) %><span class="divider">/</span></li>
        <li class="active">Trip</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">
          Trip from <%= @route.origin %> to <%= @route.destination %> <% if @current_trip.id.present? %>, Tracking Code: <%= @current_trip.tracking_code  %><% end %>
        </div>
        <div class="pull-right">
          <%= link_to "Refresh", root_path %>
        </div>
      </div>
      <div class="block-content collapse in">
        <div id="dvMap" style="width: 100%; height: 400px">
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
 $(function() {
				
    refreshLocation();
    function refreshLocation(){
         
            InitializeMap();
    }
});
</script>