config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'customers' => 'users#customer_list', :as => :customers
    post 'create_customer' => 'users#create_user', :as => :create_customer
    get 'change_status' => 'users#change_status', :as => :change_status
    get 'edit_customer' => 'users#edit_user', :as => :edit_customer
    patch 'update_customer' => 'users#update_user', :as => :update_customer
    get 'agents' => 'users#agent_list', :as => :agents
    post 'create_agent' => 'users#create_user', :as => :create_agent
    get 'edit_agent' => 'users#edit_user', :as => :edit_agent
    post 'update_agent' => 'users#update_user', :as => :update_agent
    get 'delete_agent' => 'users#delete_user', :as => :delete_agent
    get 'dashboard' => 'users#dashboard', :as => :dashboard
    get 'edit_profile' => 'users#edit_profile', :as => :edit_profile
    patch 'update_profile' => 'users#update_profile', :as => :update_profile
  end
  
  
  as :vechile do
    get 'vehicle_list' => "vehicles#vehicle_list", :as => :vehicle_list
    post 'create_vehicle' => "vehicles#create_vehicle", :as => :create_vehicle
    patch 'update_vehicle' => "vehicles#update_vehicle", :as => :update_vehicle
    get 'edit_vehicle' => "vehicles#edit_vehicle", :as => :edit_vehicle
    get 'destroy_vehicle' => "vehicles#destroy_vehicle", :as => :destroy_vehicle
  end
  
  as :route do
    get 'route_list' => "routes#route_list", :as => :route_list
    post 'create_route' => "routes#create_route", :as => :create_route
    patch 'update_route' => "routes#update_route", :as => :update_route
    get 'edit_route' => "routes#edit_route", :as => :edit_route
    get 'destroy_route' => "routes#destroy_route", :as => :destroy_route
  end
  
  as :trip do
    get 'trip_list' => "trips#trip_list", :as => :trip_list
    post 'create_trip' => "trips#create_trip", :as => :create_trip
    patch 'update_trip' => "trips#update_trip", :as => :update_trip
    get 'edit_trip' => "trips#edit_trip", :as => :edit_trip
    get 'destroy_trip' => "trips#destroy_trip", :as => :destroy_trip
    get 'stop_tracking_trip' => "trips#stop_tracking_trip", :as => :stop_tracking_trip
  end
  
  root 'home#index'
  get '/user' => "home#index", :as => 'user'
  get '/validate_authentication' => "tracking#validate_authentication", :as => 'validate_authentication'
  get '/get_trip' => "tracking#get_trip", :as => 'get_trip'
  post '/save_position' => "tracking#save_position", :as => 'save_position'
  post "/trip_details" => "home#trip_details", :as => "trip_details"

end

app/models/user.rb
class User < ActiveRecord::Base
  AGENT = "AGENT"
  ADMIN = "ADMIN"
  CUSTOMER = "CUSTOMER"

  uuid_it
  
  has_many :vehicles
  has_many :routes
  has_many :trips
  
  belongs_to :parent, :class_name => 'User', :foreign_key => :parent_id
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  
  validates :email, :presence=> true
  validates :travels_name, :presence=> true

  before_save :save_defaults

  def save_defaults
    self.authentication_code ||= rand(36**8).to_s(36)
    # If the user is a customer created by us it is ADMIN
    # If a customer creates a user they are agents
    self.user_sub_type ||= self.parent.blank? ? ADMIN : AGENT
    # User will be customer in all scenarios
    self.user_type ||= CUSTOMER
  end
  
  def is_admin?
    self.user_type == ADMIN
  end
  
  def is_customer?
    self.user_type == CUSTOMER
  end

  def is_sub_type_admin?
   self. user_sub_type == ADMIN
  end
  
  def is_sub_type_agent?
    self. user_sub_type == AGENT
  end
  
  def get_auth_code
    if self.parent_id.nil?
      self.authentication_code.upcase
    else
      self.parent.authentication_code.upcase
    end
  end

  def get_active_vehicles
    vehicles.where(:status => true, :delete_status => false)
  end

  def get_active_routes
    routes.where(:status => true, :delete_status => false)
  end
  
  def get_inactive_routes
    routes.where(:status => false, :delete_status => false)
  end

  def inactivate!
    update_attributes(:delete_status => true)
  end

  def update_status
    update_attributes(:status => self.status ^= true)
  end

  class << self
    def get_customers
      User.where("user_type = ? and user_sub_type = ?", CUSTOMER, ADMIN)
    end

    def get_active_agents(customer)
      User.where(:user_sub_type => AGENT, :parent_id => customer.id, :delete_status => false)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :set_tab, :except => [:dashboard, :edit_profile]
  before_filter :set_customer, :only => [:dashboard, :edit_profile, :update_profile]
  prepend_before_filter :authenticate_scope!
  
  def customer_list
    @customers = User.get_customers
    @user = User.new
  end
  
  def create_user
    @user = User.new(user_params)
    if !params[:id].nil?
      @customer = User.find_by_uuid(params[:id])
      @user.parent = @customer
    end
    if @user.valid?
      @user.save
      if params[:id].nil?
        redirect_to customers_path, :notice => "Successfully Created"
      else
        redirect_to agents_path(:id => @customer.uuid), :notice => "Successfully Created"
      end
    else
      if params[:id].nil?
        @customers = User.get_customers
        render :action => "customer_list"
      else
        @agents = User.get_active_agents(@customer)
        render :action => "agent_list"
      end
    end
  end
  
  def change_status
    @user = User.find_by_uuid(params[:id])
    @user.update_status
    if @user.is_sub_type_admin?
      redirect_to customers_path
    else
      customer = @user.parent
      redirect_to agents_path(:id => customer.uuid)
    end
  end
  
  def edit_user
    @user = User.find_by_uuid(params[:id])
    if @user.is_sub_type_admin?
      @customers = User.find_all_by_user_type("customer")
      render :action => "customer_list"
    else
      @customer = @user.parent
      @agents = User.get_active_agents(@customer)
      render :action => "agent_list"
    end
  end
  
  def update_user
    @user = User.find_by_uuid(params[:id])
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user.update(user_params)
    if params[:customer_id].nil?
      redirect_to customers_path, :notice => "Updated Successfully"
    else
      redirect_to agents_path(:id => params[:customer_id]), :notice => "Updated Successfully"
    end
  end
  
  def delete_user
    @user = User.find_by_uuid(params[:id])
    @user.inactivate!
    redirect_to agents_path(:id => @user.parent.uuid, :notice => "Deleted Successfully")
  end
  
  def agent_list
    @customer = User.find_by_uuid(params[:id])
    @agents = User.get_active_agents(@customer)
    @user = User.new
  end
  
  def dashboard
    @user = nil
  end
  
  def edit_profile
    @user = current_user
    render :action => "dashboard"
  end
  
  def update_profile
    if current_user.update_with_password(params[:user])
      redirect_to dashboard_path(:notice => "Successfully Updated")
    else
      @user = current_user
      render :action => "dashboard"
    end
  end
  
  private
  
  def set_customer
    puts current_user.inspect
    if current_user.is_customer? && current_user.is_sub_type_admin?
      @customer = current_user
    elsif current_user.is_sub_type_agent?
      @customer = current_user.parent
      puts current_user
      puts current_user.parent
    end
    @tab = "dashboard"
  end
  
  def set_tab
    @tab = "user"
  end

  def user_params
    params.require(:user).permit(:travels_name, :password, :password_confirmation, 
      :email, :address, :city, :state, :country, :phone, :mobile, 
      :contactus_email, :status, :delete_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_active_trips.html.erb
<table class="table table-bordered table-hover">
  <caption>Active Trips</caption>
  <thead>
    <tr>
      <th>Vehicle No:</th>
      <th>Route</th>
      <th>Tracking Code</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @customer.get_inactive_routes.each do |route| %>
      <% current_trip = route.get_current_trip %>
      <tr>
        <td><%= route.vehicle.v_no %></td>
        <td><%= route.origin %> - <%= route.destination %></td>
        <td class="text-center"><%= current_trip.tracking_code unless current_trip.nil?  %></td>
        <td class="text-center">
          <%= link_to icon_text("Trip","icon-map-marker"), trip_list_path(:rid => route.uuid) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_change_password.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>Change Password</h5>
  <ul class="nav nav-list">
    <%= form_for(@user, :url => update_password_path(:uid => @user.uuid)) do |f| %> 
    <div class="control-group">
      <%= f.password_field :password, :placeholder => "New Password*", :autocomplete => "off" %>
    </div>
    <div class="control-group">
      <%= f.password_field :password, :placeholder => "Confirm Password*", :autocomplete => "off" %>
    </div>
    <div class="control-group">
      <%= f.password_field :password, :placeholder => "Current Password*", :autocomplete => "off" %>
    </div>
      <%= f.submit "Update Password", :class => "btn btn-info", :id => "update_password" %>
    <% end %>
  </ul>
</div>

app/views/users/_edit_profile.html.erb
<%= render "users/registrations/form", :user_type => "Edit Profile", :url => update_profile_path(:uid => @user.uuid), :submit_value => "Update Profile", :id_value => "update", :change_pass => true %>

app/views/users/_profile.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-user"></i>Profile</h5>
  <ul class="nav nav-list">
    <div class="control-group">Name: <%= current_user.travels_name %> </div>
    <div class="control-group">Email: <%= current_user.email %> </div>
    <div class="control-group">Address: <%= current_user.address %> </div>
    <div class="control-group">City: <%= current_user.city %> </div>
    <div class="control-group">State: <%= current_user.state %> </div>
    <div class="control-group">Phone: <%= current_user.phone %> </div>
    <div class="control-group">Mobile: <%= current_user.mobile %> </div>
    <div class="control-group">Contact Us Email: <%= current_user.contactus_email %> </div>
    <div class="control-group"><%= button_to "Edit Profile", edit_profile_path, :class => "btn btn-info", :method => "get" %></div>
  </ul>
</div>

app/views/users/agent_list.html.erb
<div class="span3" id="sidebar">
  <% if @user != nil && @user.id != nil %>
    <%= render "users/registrations/edit" %>
  <% else %>
    <%= render "users/registrations/new" %>
  <% end %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
        <% if current_user.user_type == User::ADMIN %>
          <li><%= link_to "Customers", customers_path %><span class="divider">/</span></li>
        <% end %> 
        <li class="active">Agents</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <table class="table table-bordered table-hover">
          <caption>Agents of <%= @customer.travels_name %></caption>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @agents.each do |agent| %>
            <tr>
              <td><%= agent.travels_name %></td>
              <td><%= agent.email %></td>
              <td class="text-center">
                  <%if agent.status?  %>
                    <%= icon_text("Active", "icon-thumbs-up") %> |
                    <%= link_to icon_text("Inactivate","icon-thumbs-down"), change_status_path(:id => agent.uuid) %>
                  <% else %>
                    <%= icon_text("Inactive", "icon-thumbs-down") %> |
                    <%= link_to icon_text("Activate", "icon-thumbs-up"), change_status_path(:id => agent.uuid) %>
                  <% end %>
              </td>
              <td class="text-center delete">
                <%= link_to icon_text("Edit","icon-pencil"), edit_agent_path(:id => agent.uuid) %>
                &nbsp;|&nbsp;<%= link_to icon_text("Delete","icon-remove"), delete_agent_path(:id => agent.uuid), :class => "delete-confirm" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/customer_list.html.erb
<div class="span3" id="sidebar">
  <% if @user != nil && @user.id != nil %>
    <%= render "users/registrations/edit" %>
  <% else %>
    <%= render "users/registrations/new" %>
  <% end %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
        <li class="active">Customers</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <table class="table table-bordered table-hover">
          <caption>Customers</caption>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Auth Code</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.travels_name %></td>
              <td><%= customer.email %></td>
              <td class="text-center green"><%= customer.get_auth_code %></td>
              <td class="text-center">
                  <%if customer.status?  %>
                    <%= icon_text("Active", "icon-thumbs-up") %> |
                    <%= link_to icon_text("Inactivate","icon-thumbs-down"), change_status_path(:id => customer.uuid) %>
                  <% else %>
                    <%= icon_text("Inactive", "icon-thumbs-down") %> |
                    <%= link_to icon_text("Activate", "icon-thumbs-up"), change_status_path(:id => customer.uuid) %>
                  <% end %>
              </td>
              <td class="text-center">
                <%= link_to icon_text("Edit","icon-pencil"), edit_customer_path(:id => customer.uuid) %>
                &nbsp;|&nbsp;<%= link_to icon_text("Agents","icon-user"), agents_path(:id => customer.uuid) %>
                &nbsp;|&nbsp;<%= link_to icon_text("Vehicles","icon-forward"), vehicle_list_path(:id => customer.uuid) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="span3" id="sidebar">
  <% if @user.nil? %>
    <%= render "profile" %>
  <% else %>
    <%= render "edit_profile" %>
  <% end %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li class="active">Dashboard</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <% if !current_user.is_admin? %>
          <%= render "active_trips" %>
        <% end %>
      </div>
    </div>
  </div>
</div>