config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'customers' => 'users#customer_list', :as => :customers
    post 'create_customer' => 'users#create_user', :as => :create_customer
    get 'change_status' => 'users#change_status', :as => :change_status
    get 'edit_customer' => 'users#edit_user', :as => :edit_customer
    patch 'update_customer' => 'users#update_user', :as => :update_customer
    get 'agents' => 'users#agent_list', :as => :agents
    post 'create_agent' => 'users#create_user', :as => :create_agent
    get 'edit_agent' => 'users#edit_user', :as => :edit_agent
    post 'update_agent' => 'users#update_user', :as => :update_agent
    get 'delete_agent' => 'users#delete_user', :as => :delete_agent
    get 'dashboard' => 'users#dashboard', :as => :dashboard
    get 'edit_profile' => 'users#edit_profile', :as => :edit_profile
    patch 'update_profile' => 'users#update_profile', :as => :update_profile
  end
  
  
  as :vechile do
    get 'vehicle_list' => "vehicles#vehicle_list", :as => :vehicle_list
    post 'create_vehicle' => "vehicles#create_vehicle", :as => :create_vehicle
    patch 'update_vehicle' => "vehicles#update_vehicle", :as => :update_vehicle
    get 'edit_vehicle' => "vehicles#edit_vehicle", :as => :edit_vehicle
    get 'destroy_vehicle' => "vehicles#destroy_vehicle", :as => :destroy_vehicle
  end
  
  as :route do
    get 'route_list' => "routes#route_list", :as => :route_list
    post 'create_route' => "routes#create_route", :as => :create_route
    patch 'update_route' => "routes#update_route", :as => :update_route
    get 'edit_route' => "routes#edit_route", :as => :edit_route
    get 'destroy_route' => "routes#destroy_route", :as => :destroy_route
  end
  
  as :trip do
    get 'trip_list' => "trips#trip_list", :as => :trip_list
    post 'create_trip' => "trips#create_trip", :as => :create_trip
    patch 'update_trip' => "trips#update_trip", :as => :update_trip
    get 'edit_trip' => "trips#edit_trip", :as => :edit_trip
    get 'destroy_trip' => "trips#destroy_trip", :as => :destroy_trip
    get 'stop_tracking_trip' => "trips#stop_tracking_trip", :as => :stop_tracking_trip
  end
  
  root 'home#index'
  get '/user' => "home#index", :as => 'user'
  get '/validate_authentication' => "tracking#validate_authentication", :as => 'validate_authentication'
  get '/get_trip' => "tracking#get_trip", :as => 'get_trip'
  post '/save_position' => "tracking#save_position", :as => 'save_position'
  post "/trip_details" => "home#trip_details", :as => "trip_details"

end

app/models/route.rb
class Route < ActiveRecord::Base
  uuid_it
  belongs_to :user
  belongs_to :vehicle
  has_many :trips
  
  validates :origin, :presence=> true
  validates :destination, :presence=> true
  
  def get_previous_trips
    trips.where(:track_status => false).order("id desc")
  end

  def get_current_trip
    trips.find_by_track_status(true)
  end
  
  def fetch_current_trip
    trips.where(:track_status => true, :delete_status => false).first
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_filter :set_vehicle
  
  def route_list
    @routes = @vehicle.get_active_routes
    @route = Route.new
    respond_to do |format|
      format.html {render :action => "route_list"}
      format.json { render json: @routes }
    end
  end


  # GET /routes/1/edit
  def edit_route
    @route = Route.find_by_uuid(params[:rid])
    @routes = @vehicle.get_active_routes
    respond_to do |format|
      format.html {render :action => "route_list"}
    end
  end

  def create_route
    @route = @vehicle.routes.new(route_params)
    @route.user_id = @customer.id
    @route.created_by = current_user.id
    respond_to do |format|
      if @route.save
        format.html { redirect_to route_list_path(:vid => @vehicle.uuid), notice: 'successfully created.' }
      else
        @routes = @vehicle.get_active_routes
        format.html { render action: "route_list" }
      end
    end
  end

  # PUT /routes/1
  # PUT /routes/1.json
  def update_route
    @route = Route.find_by_uuid(params[:rid])

    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to route_list_path(:vid => @vehicle.uuid), notice: 'successfully updated.' }
      else
        @routes = @vehicle.get_active_routes
        format.html { render action: "route_list" }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy_route
    @route = Route.find_by_uuid(params[:rid])
    @route.update_attributes(:delete_status => true)

    respond_to do |format|
      format.html { redirect_to route_list_path(:vid => @vehicle.uuid), notice: 'successfully deleted.' }
    end
  end
  
  
  private
  
  def set_vehicle
    @vehicle = Vehicle.find_by_uuid(params[:vid])    
    @user = @vehicle.user
    if !@user.parent_id.nil?
      @customer = @user.parent
    else
      @customer = @user
    end
  end
  
  def route_params
    params.require(:route).permit(:destination, :origin, :status, :user_id, :vehicle_id, :delete_status)
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_edit.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>Edit Route</h5>
  <ul class="nav nav-list">
    <%= form_for(@route, :url => update_route_path(:vid => @vehicle.uuid, :rid => @route.uuid)) do |f| %>
        <% if @route.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@route.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @route.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :origin, :placeholder => 'From Station*' %>
        </div>
        <div class="control-group">
          <%= f.text_field :destination, :placeholder => "To Station*" %>
        </div>
        <%= f.submit "Update", :class => "btn btn-info", :id => "route" %>
    <% end %>
  </ul>
</div>

app/views/routes/_new.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>New Route</h5>
  <ul class="nav nav-list">
    <%= form_for(@route, :url => create_route_path(:vid => @vehicle.uuid)) do |f| %>
        <% if @route.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@route.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @route.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :origin, :placeholder => 'From Station*' %>
        </div>
        <div class="control-group">
          <%= f.text_field :destination, :placeholder => "To Station*" %>
        </div>
        <%= f.submit "Create", :class => "btn btn-info", :id => "route" %>
    <% end %>
  </ul>
</div>

app/views/routes/route_list.html.erb
<div class="span3" id="sidebar">
  <% if @route != nil && @route.id != nil %>
    <%= render "edit" %>
  <% else %>
    <%= render "new" %>
  <% end %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
        <% if current_user.user_type == User::ADMIN %>
          <li><%= link_to "Customers", customers_path %><span class="divider">/</span></li>
        <% end %> 
        <li><%= link_to "Vehicles", vehicle_list_path(:id => @customer.uuid) %><span class="divider">/</span></li>
        <li class="active">Routes</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <table class="table table-bordered table-hover">
          <caption>Route of <%= @vehicle.v_no %>(<%= @customer.travels_name %>)</caption>
          <thead>
            <tr>
              <th>From</th>
              <th>To</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @routes.each do |route| %>
            <tr>
              <td><%= route.origin %></td>
              <td><%= route.destination %></td>
              <td class="text-center">
                <%= link_to icon_text("Edit","icon-pencil"), edit_route_path(:vid => @vehicle.uuid, :rid => route.uuid) %>
                &nbsp;|&nbsp;<%= link_to icon_text("Delete","icon-remove"), destroy_route_path(:vid => @vehicle.uuid, :rid => route.uuid), :confirm => "Are you sure to delete?" %>
                &nbsp;|&nbsp;<%= link_to icon_text("Trip","icon-map-marker"), trip_list_path(:rid => route.uuid) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vehicle:</b>
  <%= @route.vehicle_id %>
</p>

<p>
  <b>User:</b>
  <%= @route.user_id %>
</p>

<p>
  <b>Origin:</b>
  <%= @route.origin %>
</p>

<p>
  <b>Destination:</b>
  <%= @route.destination %>
</p>

<p>
  <b>Status:</b>
  <%= @route.status %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>