config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'customers' => 'users#customer_list', :as => :customers
    post 'create_customer' => 'users#create_user', :as => :create_customer
    get 'change_status' => 'users#change_status', :as => :change_status
    get 'edit_customer' => 'users#edit_user', :as => :edit_customer
    patch 'update_customer' => 'users#update_user', :as => :update_customer
    get 'agents' => 'users#agent_list', :as => :agents
    post 'create_agent' => 'users#create_user', :as => :create_agent
    get 'edit_agent' => 'users#edit_user', :as => :edit_agent
    post 'update_agent' => 'users#update_user', :as => :update_agent
    get 'delete_agent' => 'users#delete_user', :as => :delete_agent
    get 'dashboard' => 'users#dashboard', :as => :dashboard
    get 'edit_profile' => 'users#edit_profile', :as => :edit_profile
    patch 'update_profile' => 'users#update_profile', :as => :update_profile
  end
  
  
  as :vechile do
    get 'vehicle_list' => "vehicles#vehicle_list", :as => :vehicle_list
    post 'create_vehicle' => "vehicles#create_vehicle", :as => :create_vehicle
    patch 'update_vehicle' => "vehicles#update_vehicle", :as => :update_vehicle
    get 'edit_vehicle' => "vehicles#edit_vehicle", :as => :edit_vehicle
    get 'destroy_vehicle' => "vehicles#destroy_vehicle", :as => :destroy_vehicle
  end
  
  as :route do
    get 'route_list' => "routes#route_list", :as => :route_list
    post 'create_route' => "routes#create_route", :as => :create_route
    patch 'update_route' => "routes#update_route", :as => :update_route
    get 'edit_route' => "routes#edit_route", :as => :edit_route
    get 'destroy_route' => "routes#destroy_route", :as => :destroy_route
  end
  
  as :trip do
    get 'trip_list' => "trips#trip_list", :as => :trip_list
    post 'create_trip' => "trips#create_trip", :as => :create_trip
    patch 'update_trip' => "trips#update_trip", :as => :update_trip
    get 'edit_trip' => "trips#edit_trip", :as => :edit_trip
    get 'destroy_trip' => "trips#destroy_trip", :as => :destroy_trip
    get 'stop_tracking_trip' => "trips#stop_tracking_trip", :as => :stop_tracking_trip
  end
  
  root 'home#index'
  get '/user' => "home#index", :as => 'user'
  get '/validate_authentication' => "tracking#validate_authentication", :as => 'validate_authentication'
  get '/get_trip' => "tracking#get_trip", :as => 'get_trip'
  post '/save_position' => "tracking#save_position", :as => 'save_position'
  post "/trip_details" => "home#trip_details", :as => "trip_details"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  uuid_it
  
  belongs_to :user
  has_many :routes
  
  validates :v_no, :presence=> true
  
  def get_active_routes
    routes.where(:delete_status => false)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_filter :set_user_and_customer
  before_filter :set_tab
  
  def vehicle_list
    @vehicles = @customer.get_active_vehicles
    @vehicle = Vehicle.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  def edit_vehicle
    @vehicle = Vehicle.find_by_uuid(params[:vid])
    @vehicles = @customer.get_active_vehicles
    respond_to do |format|
      format.html {render :action => "vehicle_list"}
    end
  end

  # POST /vehicles
  # POST /vehicles.json
  def create_vehicle
    @vehicle = @customer.vehicles.new(vehicle_params)
    @vehicle.status = true
    @vehicle.created_by = current_user.id
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_list_path(:id => @user.uuid), notice: 'successfully created.' }
      else
        @vehicles = @customer.get_active_vehicles
        format.html { render action: "vehicle_list" }
      end
    end
  end

  def update_vehicle
    @vehicle = Vehicle.find_by_uuid(params[:vid])

    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_list_path(:id => @user.uuid), notice: 'successfully updated.' }
      else
        @vehicles = @customer.get_active_vehicles
        format.html { render action: "vehicle_list" }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy_vehicle
    @vehicle = Vehicle.find_by_uuid(params[:vid])
    @vehicle.update_attributes(:delete_status => true)

    respond_to do |format|
      format.html { redirect_to vehicle_list_path(:id => @user.uuid), notice: 'successfully deleted.' }
    end
  end
  
  private
  
  def set_user_and_customer
    @user = User.find_by_uuid(params[:id])
    if !@user.parent_id.nil?
      @customer = @user.parent
    else
      @customer = @user
    end
  end
  
  def set_tab
    @tab = "vehicle"
  end
  
  def vehicle_params
    params.require(:vehicle).permit(:user_id, :v_name, :v_no, :v_seat_type, 
      :v_type, :status, :delete_status)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_edit.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>Edit Vehicle</h5>
  <ul class="nav nav-list">
    <%= form_for(@vehicle, :url => update_vehicle_path(:id => @user.uuid, :vid => @vehicle.uuid)) do |f| %>
        <% if @vehicle.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @vehicle.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :v_no, :placeholder => 'Vehicle Number*' %>
        </div>
        <div class="control-group">
          <%= f.text_field :v_name, :placeholder => "Vechile Name" %>
        </div>
        <%= f.submit "Update", :class => "btn btn-info", :id => "vehicle" %>
    <% end %>
  </ul>
</div>

app/views/vehicles/_new.html.erb
<div class="navbar navbar-inner">
  <h5><i class="icon-plus"></i>New Vehicle</h5>
  <ul class="nav nav-list">
    <%= form_for(@vehicle, :url => create_vehicle_path(:id => @user.uuid)) do |f| %>
        <% if @vehicle.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
            <ul>
            <% @vehicle.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div id="msg"></div>
        <div id="messageDiv">
          <%- flash.each do |name, msg| -%>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class=> "alert" if msg.is_a?(String) %>
          <%- end -%>
        </div>
        <div class="control-group">
          <%= f.text_field :v_no, :placeholder => 'Vehicle Number*' %>
        </div>
        <div class="control-group">
          <%= f.text_field :v_name, :placeholder => "Vechile Name" %>
        </div>
        <%= f.submit "Create", :class => "btn btn-info", :id => "vehicle" %>
    <% end %>
  </ul>
</div>

app/views/vehicles/vehicle_list.html.erb
<div class="span3" id="sidebar">
  <% if @vehicle != nil && @vehicle.id != nil %>
    <%= render "edit" %>
  <% else %>
    <%= render "new" %>
  <% end %>
</div>

<div class="span9" id="content">
  <div class="row-fluid">
    <div id="breadcrumb">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %><span class="divider">/</span></li>
        <% if current_user.user_type == User::ADMIN %>
          <li><%= link_to "Customers", customers_path %><span class="divider">/</span></li>
        <% end %>  
        <li class="active">Vehicles</li>
      </ul>
    </div>
    <div class="block">
      <div class="navbar navbar-inner block-header">
        <table class="table table-bordered table-hover">
          <caption>Vechile List of <%= @customer.travels_name %></caption>
          <thead>
            <tr>
              <th>Vehicle No:</th>
              <th>Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @vehicles.each do |vehicle| %>
            <tr>
              <td><%= vehicle.v_no %></td>
              <td><%= vehicle.v_name %></td>
              <td class="text-center">
                <%= link_to icon_text("Edit","icon-pencil"), edit_vehicle_path(:id => @user.uuid, :vid => vehicle.uuid) %>
                &nbsp;|&nbsp;<%= link_to icon_text("Delete","icon-remove"), destroy_vehicle_path(:id => @user.uuid, :vid => vehicle.uuid), :confirm => "Are you sure you want to delete this vehicle?" %>
                &nbsp;|&nbsp;<%= link_to icon_text("Routes","icon-road"), route_list_path(:id => @user.uuid, :vid => vehicle.uuid) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>